#' Subtotal Row Addition Function

#' @description Adds subtotal rows to a data report. Designed to work with reports generated by group_by + summarise.

#' @param report A data report.
#' @param frame Data frame summarised by the data report.
#' @param vars Names of column(s) in the data frame aggregated in the data report.
#' @param aggregator Function to aggregate the data with.
#' @param exclude Vector of column indices determining which variables don't require subtotal rows.
#' @param agg_parameter A named list of optional parameter(s) for the aggregation function to use.
#' @param subtotal_label Label to be used for subtotal rows.

#' @details The dataset and report are factorized, and a series of reports are generated.
#' These reports are structured after the original one - using the same grouping variables,
#' as well as aggregating the given variables with the given aggregation function and optional parameters.
#' For best results, choose the same variables and aggregator used to generate the original report.
#' Each generated report has some grouping variables replaced by a subtotal label,
#' effectively concentrating all levels of those variables
#' into one subtotal row for those variables.
#' The subtotal reports are all combined with the original report,
#' and the combined report is grouped and sorted, sorting the subtotal label to the top for all variables.

#' @return The grouped data report with subtotal rows included.
#' @export

#' @examples
#' library(dplyr)
#'
#' group_by(iris, Species, Petal.Width) %>%
#' summarise(sum(Petal.Length), .groups = "keep") %>%
#' subtotal_row(iris, vars = "Petal.Length")
#'
#' group_by(iris, Species, Petal.Width) %>%
#' summarise(mean(Sepal.Width), .groups = "keep") %>%
#' subtotal_row(iris, vars = "Sepal.Width", aggregator = "mean")
#'
#' group_by(mtcars, cyl, gear, carb) %>%
#' summarise(median(wt), median(hp), .groups = "keep") %>%
#' subtotal_row(mtcars, vars = c("wt", "hp"), aggregator = "median")
#'
#' group_by(mtcars, cyl, gear, carb) %>%
#' summarise(Med_Weight = median(wt), Med_Hrspw = median(hp), .groups = "keep") %>%
#' subtotal_row(mtcars, vars = c("wt", "hp"), aggregator = "median", exclude = 1)
#'
#' group_by(mtcars, vs, am, drat, carb) %>%
#' summarise(min(mpg), min(disp), min(carb), .groups = "keep") %>%
#' subtotal_row(mtcars, vars = c("mpg", "disp", "carb"),
#' aggregator = "min", exclude = c(2, 4),
#' subtotal_label = "Min_Cars_Total", agg_parameter = list(na.rm = TRUE))

subtotal_row <- function(report, frame, vars = "Population", aggregator = "sum", exclude = numeric(0),
                         agg_parameter = list(), subtotal_label = "Total"){

  handled <- subtotal_error_handle(report, frame, vars, aggregator, exclude, agg_parameter, subtotal_label)
  frame <- handled$frame
  vars <- handled$vars
  aggregator <- handled$aggregator
  report <- handled$report

  include_vec <- list()
  final_label <- ncol(report) - length(vars)
  label_cols <- 1:final_label
  label_names <- names(report)[label_cols]

  factor_report <- mutate(report, across(all_of(label_cols), function(x){if(is.factor(x)){x} else {factor(x)}}))
  report_levels <- lapply(factor_report[,label_cols], function(x){unique(levels(x))})
  report_levels_subtotal <- lapply(report_levels, function(x){c(subtotal_label, x)})
  select_frame <- select(frame, all_of(c(label_names, vars)))
  select_frame <- mutate(select_frame, across(all_of(label_cols), function(x){
    if(is.factor(x)){x} else {factor(x, levels = report_levels[[cur_column()]])}}))

  for (i in label_cols){
    include_vec[[i]] <- i:final_label
  }

  if (length(exclude) > 0){
    exclude_vec <- !(1:final_label %in% exclude)
    include_vec <- include_vec[exclude_vec]
  }


  report_list <- list(report)
  for (j in 1:length(include_vec)){
    mutate_frame <- mutate(select_frame, across(all_of(include_vec[[j]]), function(x){x = factor(subtotal_label)}))
    if (length(agg_parameter) == 0){
      mutate_report <- group_by(mutate_frame, across(all_of(label_cols))) %>% summarise(
        across(all_of(vars), aggregator), .groups = "drop")
    }
    else {
      mutate_report <- tryCatch({group_by(mutate_frame, across(all_of(label_cols))) %>% summarise(across(all_of(vars),
                        function(x){rlang::exec(aggregator, x, !!!agg_parameter)}), .groups = "drop")},
                          error = function(e) {if(j == 1){warning(
                          "\nWarning: The provided aggregation parameters caused an error. ",
                          "Falling back to default aggregation without parameters.\n", call. = FALSE)}
                          group_by(mutate_frame, across(all_of(label_cols))) %>% summarise(
                          across(all_of(vars), aggregator), .groups = "drop")})
    }
    names(mutate_report) <- names(report)
    report_list[[j+1]] <- mutate_report
  }
  final_report <- do.call(rbind, c(report_list, make.row.names = FALSE))
  final_report <- mutate(final_report, across(all_of(label_cols),
                          function(x){x <- as.character(x)
                          factor(x, levels = report_levels_subtotal[[cur_column()]])}))

  final_report_vars <- select(final_report, -all_of(label_cols))
  if (any(is.na(final_report_vars))) {
    warning("NA values detected in output. Setting agg_parameter to \"na.rm\" may resolve this.")
  }
  if (any(sapply(final_report_vars, function(x) is.infinite(x) | is.nan(x)))) {
    warning("Infinite or NaN values detected in output. Your data may contain infinite or NaN values.")
  }

  final_report <- arrange(final_report, across(all_of(label_cols)))
  group_by(final_report, across(all_of(label_names)))
}
